import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import type { State, Task } from "../model.js";
import { atomicWrite, readFileSafe } from "./lock.js";
import { parseBacklog, renderTaskLines } from "./markdown-grammar.js";

/**
 * The read-only markdown mirror.
 *
 * Rendered on every successful sync, it is what makes the linear backend
 * degrade gracefully: with the network blocked a read still has a complete,
 * recent picture of the backlog on disk, in exactly the format a markdown home
 * would have (ticket DEV-44 acceptance criterion 4). It is derived data and
 * never a write target - editing it changes nothing in Linear - so it carries
 * a banner saying so.
 *
 * It is rendered through the markdown grammar's own `renderTaskLines`, so the
 * mirror is a genuine tasks-axi backlog file rather than a lookalike, and any
 * other tool that reads `data/backlog.md` keeps working unchanged.
 */

const ORDER: State[] = ["in_flight", "queued", "done"];
const HEADERS: Record<State, string> = {
  in_flight: "## In flight",
  queued: "## Queued",
  done: "## Done",
};

export interface MirrorMeta {
  team: string;
  project: string;
  /** ISO timestamp of the sync that produced this mirror. */
  syncedAt: string;
}

export function mirrorText(tasks: Task[], meta: MirrorMeta): string {
  const lines: string[] = [
    "# Backlog (mirror)",
    "",
    `<!-- Generated by tasks-axi from Linear team ${meta.team}, project ${meta.project} at ${meta.syncedAt}.`,
    "     Read-only: edits here are never written back. Use `tasks-axi` to change a task. -->",
    "",
  ];
  for (const state of ORDER) {
    lines.push(HEADERS[state]);
    for (const task of tasks.filter((candidate) => candidate.state === state)) {
      lines.push(...renderTaskLines(task));
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderMirror(
  path: string,
  tasks: Task[],
  meta: MirrorMeta,
): void {
  mkdirSync(dirname(path), { recursive: true });
  atomicWrite(path, mirrorText(tasks, meta));
}

/**
 * Read the mirror back as tasks. This is the offline read path, and it parses
 * with the markdown grammar for the same reason the mirror is rendered with
 * it: there is exactly one markdown backlog format, not two.
 */
export function readMirrorTasks(path: string): Task[] {
  const source = readFileSafe(path);
  if (!source) return [];
  const doc = parseBacklog(source);
  const tasks: Task[] = [];
  for (const section of doc.sections) {
    for (const entry of section.entries) {
      if (entry.kind === "task") tasks.push(entry.task);
    }
  }
  return tasks;
}
